### ISSUE TITLE
Idea: turn into a smart contract

### ISSUE THREAD

**Issue by brunowowk** [badublanc/bots-lilnouns-settler#1]
What are your thoughts on converting the bot into a smart contract relying on https://www.gelato.network/ to auto-execute the settlements?

This way it could be transferred to the DAO, so it's controlled via snapshot voting. Also, you wouldn't need to maintain the script infrastructure.

**Comment by badublanc** [comment]
I initially wanted to use a smart contract, but opted for a script because contracts need a trigger in order to execute. I'm not familiar with Gelato but would be open to revisiting. 

That said, this script is running on a cron job and I haven't touched it since it was deployed. Feel free to take a stab at porting to Gelato if you get a chance!
